name: Todo application deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

  name: checkout code
  steps:
    -uses: action/checkout@v4

  name: Deploy
  runs: |
    cd /apps/devops-projects/project_2/
    git pull main
    docker compose up --build -d
