apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ep
  name: backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command:
        - sh
        - -c
        - |
          until nc -z postgres 5432
          do
            echo "Waiting for postgres..."
            sleep 2
          done
      containers:
      - name: backend
        image: yugal47/employeeportalbackend:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: db_host

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: db_port

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: db_name

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
